#!/usr/bin/env zsh
# Generate ~/.ssh/config.d/allhosts grouped by Tenant from NetBox IPAddresses
# Optional tag filter; deduplicates correctly.

NETBOX_URL="https://netbox.corp.safersoftware.net"
#NETBOX_TOKEN=
#!/usr/bin/env zsh
set -euo pipefail
IFS=$'\n\t'

NETBOX_URL="${NETBOX_URL:-}"
NETBOX_TOKEN="${NETBOX_TOKEN:-}"
TAG="${TAG:-}"
USER_NAME="${USER_NAME:-admin}"
PORT="${PORT:-44040}"
PROXYJUMP="${PROXYJUMP:-bastion}"
OUTFILE="${OUTFILE:-$HOME/.ssh/config.d/allhosts}"
TEMP="$(mktemp -t netbox_sshgen.XXXXXX)"
LIMIT=1000

[[ -z "$NETBOX_URL" || -z "$NETBOX_TOKEN" ]] && {
  echo "Usage: NETBOX_URL=https://... NETBOX_TOKEN=xxx [TAG=mytag] ./netbox_sshgen_flat.zsh"
  exit 1
}
command -v jq >/dev/null || { echo "jq required"; exit 1; }
command -v curl >/dev/null || { echo "curl required"; exit 1; }

mkdir -p "$(dirname "$OUTFILE")"

echo "# Autogenerated from NetBox $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >| "$TEMP"
echo "# Source: $NETBOX_URL ${TAG:+Tag=$TAG}" >> "$TEMP"
echo "" >> "$TEMP"

url="${NETBOX_URL%/}/api/ipam/ip-addresses/?limit=${LIMIT}"
[[ -n "$TAG" ]] && url="${url}&tag=${TAG}"

alljson="$(mktemp -t alljson.XXXXXX)"
echo '{"results":[]}' > "$alljson"

while [[ -n "$url" && "$url" != "null" ]]; do
  resp="$(curl -sSf -H "Authorization: Token ${NETBOX_TOKEN}" "$url")"
  jq -s '{results: (.[0].results + .[1].results)}' "$alljson" <(echo "$resp") > "${alljson}.new"
  mv "${alljson}.new" "$alljson"
  url="$(echo "$resp" | jq -r '.next')"
done

# --- Render SSH blocks flat, tenant as comment ---
jq -r --arg USER "$USER_NAME" --arg PORT "$PORT" --arg PJ "$PROXYJUMP" '
  .results
  | map({
      addr: (.address | split("/")[0]),
      desc: (.description // ""),
      tenant: (.tenant.name // "Unassigned")
    })
  | unique_by(.addr + ":" + .desc + ":" + .tenant)
  | map(select(.desc != "" and .addr != ""))
  | .[]
  | "Host \(.desc)\n  HostName \(.addr)\n  User \($USER)\n  Port \($PORT)\n  ProxyJump \($PJ)\n  ServerAliveInterval \(30)\n  # Tenant: \(.tenant)\n"
' "$alljson" >> "$TEMP"

mv -f "$TEMP" "$OUTFILE"
chmod 600 "$OUTFILE"
rm -f "$alljson"

hosts=$(grep -c '^Host ' "$OUTFILE" || true)
echo "✅ Wrote $hosts hosts → $OUTFILE"
echo "Ensure your ~/.ssh/config includes:  Include ~/.ssh/config.d/*"
