{
 "title": "Taiwan Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "ZL --> AWS INFRA",
   "type": "stat",
   "description": "Functional Latency to Open TCP Port to remote service",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connect_time_ms{source=\"ZL-TPE\"}",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CP --> AWS INFRA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connect_time_ms{source=\"CP-TPE\"}",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Zenlayer ---> World",
   "type": "stat",
   "description": "Latency times from Zenlayer",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(network_latency_ms{source=\"ZL-TPE\"}[5m])",
     "legendFormat": " {{dest}} "
    }
   ]
  },
  {
   "title": "CP Gateway Ping times",
   "type": "stat",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(network_latency_ms{source=\"CP-TPE\"}[5m])",
     "legendFormat": "{{dest}} "
    }
   ]
  },
  {
   "title": "ZL-TPE Jitter Performance Impact",
   "type": "timeseries",
   "description": "How the deviation of ping times impact application performance",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "stddev_over_time(network_latency_ms{source=\"ZL-TPE\", proto=\"icmp\"}[10m])",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "CP-TPE Jitter Performance Impact",
   "type": "timeseries",
   "description": "How the deviation of ping times impact application performance",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "stddev_over_time(network_latency_ms{source=\"CP-TPE\", proto=\"icmp\"}[10m])",
     "legendFormat": "{{dest}}"
    }
   ]
  }
 ]
}