{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SDP / VECTOR REACHABLE",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "network_connectivity{}", "legendFormat": "{{source}} {{dest}} {{port}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Ping times",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 20, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "network_latency_ms{}", "legendFormat": "{{source}} --> {{dest}} " }
   ]
  },
  {
   "title": "Jitter Impact on Performance",
   "type": "timeseries",
   "description": "How the deviation of ping times impact application performance",
   "gridPos": { "h": 19, "w": 20, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "stddev_over_time(network_latency_ms{}[1m])",
     "legendFormat": "{{source}} --> {{dest}} "
    }
   ]
  }
 ]
}