{
 "title": "IPerf Testing",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "{job=\"speedtest\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Iperf Source --- Destination",
   "type": "timeseries",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "iperf3_bits_per_second{proto=\"udp\"}",
     "legendFormat": "{{proto}} {{source}} {{dest}}"
    },
    {
     "expr": "iperf3_bits_per_second{proto=\"tcp\"}",
     "legendFormat": "{{proto}} {{source}} {{dest}}"
    }
   ]
  },
  {
   "title": "Average EWR - IPERF ---> Remote",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 15, "w": 23, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "iperf3_bits_per_second{}",
     "legendFormat": " {{proto}}  {{source}} {{dest}}"
    }
   ]
  },
  {
   "title": "ICMP Latemcy",
   "type": "timeseries",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "iperf3_latency_ms{proto=~\"icmp\"}",
     "legendFormat": "{{source}} {{dest}}"
    }
   ]
  }
 ]
}